#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

ERROR='\033[1;33m'
NC='\033[0m'

length=$(eval "git rev-list --count HEAD ^origin/master");

if ! $length -eq 1; then
  echo "${ERROR}You have \"$length\" commits ahead origin/master. abort${NC}";
  exit 1;
fi